language: node_js
node_js:
  - 8
  
script:
  - npm install -g snyk
  - snyk monitor --all-projects # Autodetect all projects in working directory, scan and publish results to Snyk
  - snyk test --all-projects # Autodetect all projects in working directory
