install:
  - pip install pipenv
language: node_js
node_js:
  - lts/*
script:
  - npm install -g snyk@latest
  - snyk -v
  - snyk code
  - snyk test --docker debian --file=Dockerfile --exclude-base-image-vulns
  - snyk test lodash --dev 
  - snyk test ionic@1.6.5 --dev
